export const FETCH_RESTAURANT_DETAIL = 'FETCH_RESTAURANT_DETAIL';
export const SAVE_RESTAURANT_DETAIL = 'SAVE_RESTAURANT_DETAIL';
export const FAILED_FETCH_RESTAURANT_DETAIL = 'FAILED_FETCH_RESTAURANT_DETAIL';

export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const SAVE_REVIEWS = 'SAVE_REVIEWS';
export const FAILED_FETCH_REVIEWS = 'FAILED_FETCH_REVIEWS';

export const SEND_REVIEW = 'SEND_REVIEW';
export const SET_RATE = 'SET_RATE';
