export const FETCH_RESTAURANTS_LIST = 'FETCH_RESTAURANTS_LIST';
export const SAVE_RESTAURANTS_LIST = 'SAVE_RESTAURANTS_LIST';
export const FAILED_FETCH_RESTAURANTS_LIST = 'FAILED_FETCH_RESTAURANTS_LIST';
